# Generated by Django 5.0.2 on 2024-02-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(default="1992-04-05"),
            preserve_default=False,
        ),
    ]
