# Generated by Django 5.0.2 on 2024-02-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "male"), ("F", "female"), ("O", "other")],
                default="F",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
