# Generated by Django 5.0.2 on 2024-02-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_description_user_latitude_user_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "male"), ("F", "female"), ("O", "other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
